version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: ask-her-valentine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - web
networks:
  web:
    driver: bridge